name: younifirst_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  intl: ^0.19.0
  url_launcher: ^6.2.5
    

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^6.0.0

flutter:

  assets: 
  - assets/images/Bintang.png
  - assets/images/Interaksi.png
  - assets/images/Lingkaran dalam.png
  - assets/images/Topi Wisuda.png
  - assets/images/Younifirst.png
  - assets/images/background_login.png
  - assets/images/icon_login.png
  - assets/images/item_login.png
  - assets/images/logo.png
  - assets/images/logo_putih.png

  uses-material-design: true
  
